### ISSUE TITLE
"Warning: The set-output command is deprecated and will be disabled soon." 

### ISSUE THREAD

**Issue by Universal-Omega** [technote-space/workflow-conclusion-action#113]
> Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

@actions/core probably needs updated to 1.10.0?

Is shown in console when CI is running.

**Comment by alonbl** [comment]
Please update the dependencies using `npm update`, you will notice that `@actions/core` is upgraded to `1.10.0` which contains a fix to the github deprecation.

Reference: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by alonbl** [comment]
This is fixed in latest tag.

**Comment by Zamiell** [comment]
I guess we'll need to fork this since the creator has disappeared. Does someone want to volunteer to set up `workflow-conclusion-action-2`?
