### ISSUE TITLE
Getting the job output from the print

### ISSUE THREAD

**Issue by strboul** [technote-space/workflow-conclusion-action#87]
## Please describe your suggestion: 提案の概要

I'm frustrated that I cannot get the print output (`jobs`) from the action. The report is printed onto the `stdout` via `console.log`.

## Describe the solution you'd like: 考えうる解決方法
I'd like to get the output in a file or env variable so I can use it in the next step.
How to do that?

## Additional context: 補足
![image](https://user-images.githubusercontent.com/25015317/143886852-f916a0f0-6a37-4f45-a46d-2a1ee3310862.png)

**Comment by technote-space** [comment]
This Actions is not intended to obtain a list of jobs.
